<?php

namespace Application\Repository;

/**
 * Activity
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Activity extends \Doctrine\ORM\EntityRepository
{
}
