<?php

namespace Application\Repository;

/**
 * Article
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Article extends \Doctrine\ORM\EntityRepository
{
}
