<?php

namespace Application\Repository;

/**
 * EmployeeUnit
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeUnit extends \Doctrine\ORM\EntityRepository
{
}
