<?php

namespace Application\Repository;

/**
 * Highlights
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Highlights extends \Doctrine\ORM\EntityRepository
{
}
