<?php

namespace Application\Repository;

/**
 * Itinerary
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Itinerary extends \Doctrine\ORM\EntityRepository
{
}
