<?php

namespace Application\Repository;

/**
 * ItineraryRoute
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItineraryRoute extends \Doctrine\ORM\EntityRepository
{
}
