<?php

namespace Application\Repository;

/**
 * ItineraryCity
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItineraryCity extends \Doctrine\ORM\EntityRepository
{
}
