<?php

namespace Application\Repository;

/**
 * Warning
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Warning extends \Doctrine\ORM\EntityRepository
{
}
