<!DOCTYPE html>
<html lang="pt-br">
<head>
    <?php echo $this->headTitle('Nivea')->setSeparator(' / ')->setAutoEscape(false) . PHP_EOL; ?>

    <!-- BEGIN META -->
    <meta charset="UTF-8" />
    <?php
    echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        . PHP_EOL;
    ?>
    <!-- END META -->

    <!-- BEGIN STYLESHEETS -->
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/images/favicon.ico'))
            ->prependStylesheet($this->basePath('/assets/materialadmin/assets/css/theme-1/material-design-iconic-font.min.css'))
//            ->prependStylesheet($this->basePath('/assets/bower_components/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('/assets/materialadmin/assets/css/theme-1/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('/assets/materialadmin/assets/css/theme-1/materialadmin.css'))
            ->prependStylesheet($this->basePath('/assets/materialadmin/assets/css/theme-1/bootstrap.css'))
//            ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,100,300,400,500,700,900')
            ->appendStylesheet($this->basePath('/assets/css/error.css'))
        . PHP_EOL;
    ?>
    <!-- END STYLESHEETS -->

    <!-- BEGIN JAVASCRIPT -->
    <?php
    echo $this->headScript()
            ->appendFile($this->basePath('/assets/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('/assets/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        . PHP_EOL;
    ?>
    <!-- END JAVASCRIPT -->
</head>

<body>
    <!-- BEGIN SECTION-->
    <section>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="row" id="error_header">
                    <div class="col-md-12">
                        <a href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('/assets/images/logo_nivea.png');?>" class="center-block"></a>
                    </div>
                </div>

                <div class="row" id="error_content">
                    <div class="col-md-12">

                        <?php echo $this->content; ?>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END SECTION-->

    <!-- BEGIN FOOTER-->
    <section>
        <div class="row">
            <div class="col-md-4 col-lg-offset-4">
                <span class="opacity-75">Copyright &copy; <?php echo date('Y');?></span> <strong>Beirsdorf</strong>
            </div>
        </div>
    </section>
    <!-- END FOOTER-->
</body>
</html>