<!DOCTYPE html>
<html lang="pt-br">
<head>
    <?php echo $this->headTitle('Nivea')->setSeparator(' / ')->setAutoEscape(false) . PHP_EOL; ?>

    <!-- BEGIN META -->
    <meta charset="UTF-8" />
    <?php
    echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        . PHP_EOL;
    ?>
    <!-- END META -->

    <!-- BEGIN STYLESHEETS -->
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/images/favicon.ico'))
            ->prependStylesheet($this->basePath('/assets/materialadmin/assets/css/theme-1/material-design-iconic-font.min.css'))
            ->prependStylesheet($this->basePath('/assets/bower_components/font-awesome/css/font-awesome.min.css'))
//            ->prependStylesheet($this->basePath('/assets/materialadmin/assets/css/theme-1/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('/assets/materialadmin/assets/css/theme-1/materialadmin.css'))
            ->prependStylesheet($this->basePath('/assets/materialadmin/assets/css/theme-1/bootstrap.css'))
            ->prependStylesheet($this->basePath('/assets/materialadmin/assets/css/theme-default/libs/toastr/toastr.css'))
            ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900')
        . PHP_EOL;
    ?>
    <!-- END STYLESHEETS -->

    <!-- BEGIN JAVASCRIPT -->
    <?php
    echo $this->headScript()
            ->prependFile($this->basePath('/assets/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('/assets/js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('/assets/materialadmin/assets/js/libs/nanoscroller/jquery.nanoscroller.min.js'))
            ->prependFile($this->basePath('/assets/materialadmin/assets/js/libs/autosize/jquery.autosize.min.js'))
            ->prependFile($this->basePath('/assets/materialadmin/assets/js/libs/spin.js/spin.min.js'))
            ->prependFile($this->basePath('/assets/materialadmin/assets/js/libs/bootstrap/bootstrap.min.js'))
            ->prependFile($this->basePath('/assets/materialadmin/assets/js/libs/jquery/jquery-migrate-1.2.1.min.js'))
            ->prependFile($this->basePath('/assets/materialadmin/assets/js/libs/jquery/jquery-1.11.2.min.js'))
        . PHP_EOL;
    ?>
    <!-- END JAVASCRIPT -->
</head>
<body class="header-fixed menubar-first">

<?php echo $this->partial('partials/layout/flash_message.phtml');?>

<div id="load_modal"></div>

    <!-- BEGIN HEADER-->
    <header id="header" >
        <div class="headerbar">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="headerbar-left">
                <ul class="header-nav header-nav-options">
                    <li class="header-nav-brand" >
                        <div class="brand-holder">
                            <a href="<?php echo $this->url('home') ?>">
                                <span class="text-lg text-bold text-primary">NIVEA</span>
                            </a>
                        </div>
                    </li>
                    <li>
                        <a class="btn btn-icon-toggle menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                            <i class="fa fa-bars"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="headerbar-right">
                <ul class="header-nav header-nav-profile">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle ink-reaction" data-toggle="dropdown">
                            <img src="<?php echo $this->basePath('/assets/images/logo_nivea.png');?>" alt="" />
                                <span class="profile-info">
                                    <?php echo ($this->zfcUserIdentity() ? $this->zfcUserIdentity()->getDisplayname() : '') . PHP_EOL; ?>
                                    <small>Administrator</small>
                                </span>
                        </a>
                        <ul class="dropdown-menu animation-dock">
                            <li><a href="<?php echo $this->url('zfcuser/logout') ?>"><i class="fa fa-fw fa-power-off text-danger"></i> Logout</a></li>
                        </ul><!--end .dropdown-menu -->
                    </li><!--end .dropdown -->
                </ul><!--end .header-nav-profile -->
            </div><!--end #header-navbar-collapse -->
        </div>
    </header>
    <!-- END HEADER-->

    <!-- BEGIN BASE-->
    <div id="base">

        <!-- BEGIN CONTENT-->
        <div id="content">

            <!-- BEGIN BLANK SECTION -->

<?php echo $this->content; ?>

            <!-- END BLANK SECTION -->

        </div><!--end #content-->
        <!-- END CONTENT -->

        <!-- BEGIN MENUBAR-->
        <div id="menubar" class="menubar-inverse ">
            <div class="menubar-fixed-panel">
                <div>
                    <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>
                <div class="expanded">
                    <a href="<?php echo $this->url('home') ?>">
                        <span class="text-lg text-bold text-primary ">NIVEA</span>
                    </a>
                </div>
            </div>
            <div class="menubar-scroll-panel">

                <!-- BEGIN MAIN MENU -->
<?php $partial = ['partials/navigation/menu.main.phtml', 'default']; ?>
<?php $this->navigation('navigation')->menu()->setPartial($partial); ?>
<?php echo $this->navigation('navigation')->menu()->render(); ?>
                <!-- END MAIN MENU -->

                <div class="menubar-foot-panel">
                    <small class="no-linebreak hidden-folded">
                        <span class="opacity-75">Copyright &copy; <?php echo date('Y');?></span> <strong>Beirsdorf</strong>
                    </small>
                </div>
            </div><!--end .menubar-scroll-panel-->
        </div><!--end #menubar-->
        <!-- END MENUBAR -->

    </div><!--end #base-->
    <!-- END BASE -->

    <!-- BEGIN JAVASCRIPT -->
    <?php
    echo $this->inlineScript()
            ->appendFile($this->basePath('/assets/materialadmin/assets/js/core/source/App.js'))
            ->appendFile($this->basePath('/assets/materialadmin/assets/js/core/source/AppNavigation.js'))
            ->appendFile($this->basePath('/assets/materialadmin/assets/js/core/source/AppOffcanvas.js'))
            ->appendFile($this->basePath('/assets/materialadmin/assets/js/core/source/AppCard.js'))
            ->appendFile($this->basePath('/assets/materialadmin/assets/js/core/source/AppForm.js'))
            ->appendFile($this->basePath('/assets/materialadmin/assets/js/core/source/AppNavSearch.js'))
            ->appendFile($this->basePath('/assets/materialadmin/assets/js/core/source/AppVendor.js'))
            ->appendFile($this->basePath('/assets/materialadmin/assets/js/libs/toastr/toastr.js'))
        . PHP_EOL;
    ?>
    <!-- END JAVASCRIPT -->
</body>
</html>