<!-- BEGIN BREADCRUMB -->
<?php
/**
 * @var $breadcrumbs \Zend\View\Helper\Navigation\Breadcrumbs
 * @var $navigation \Zend\Navigation\Navigation
 */

$breadcrumbs = $this->navigation('navigation')->breadcrumbs();
$navigation = $breadcrumbs->getContainer();
?>
<div class="section-header">
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('home') ?>">Home</a></li>
<?php
    foreach($this->pages as $page):
        if(!$page->isActive()):
?>
        <li><a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a></li>
<?php
        else:
?>
        <li class="active"><?php echo $page->getLabel(); ?></li>
<?php
        endif;
    endforeach;
?>
    </ol>
</div><!--end .section-header -->

<!-- END BREADCRUMB -->