<?php
$this->headTitle('Login');

$form = $this->loginForm;
$form->setAttributes(array('class' => 'form'));
$form->prepare();
?>

<!-- BEGIN TITLE -->
<?php echo $this->partial('partials/simple/title.phtml', array('title' => $this->headTitle()->setSeparator(' / ')->renderTitle())); ?>
<!-- END TITLE -->

<!-- BEGIN FORM -->
<div class="row">
    <div class="col-md-12">
        <div class="form_login">
            <section>
                <form method="POST" class="form">
                <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                <?php endif ?>

                    <div class="form-group">
                        <?php echo $this->formInput($form->get('identity')->setAttributes(array('class' => 'form-control', 'placeholder' => ''))) . PHP_EOL; ?>
                        <?php echo $this->formLabel($form->get('identity')) . PHP_EOL; ?>
                    </div>

                    <div class="form-group">
                        <?php echo $this->formInput($form->get('credential')->setAttributes(array('class' => 'form-control', 'placeholder' => ''))) . PHP_EOL; ?>
                        <?php echo $this->formLabel($form->get('credential')) . PHP_EOL; ?>
                    </div>

                    <div class="row">
                        <div class="col-md-12 text-right">
                            <?php echo $this->formButton($form->get('submit')->setAttributes(array('class' => 'btn btn-primary ink-reaction btn-raised'))) . PHP_EOL; ?>
                        </div>
                    </div>
                </form>
            </section>

            <?php if ($this->enableRegistration) : ?>
                <section class="not_register">
                    <div class="row">
                        <div class="col-md-12">
                            <p>
                                Não registrado? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>">Registre-se agora</a>
                            </p>
                        </div>
                    </div>
                </section>
            <?php endif; ?>
        </div>
    </div>
</div>
<!-- END FORM -->